version: '3.8'

services:
  detector:
    build:
      context: .
      dockerfile: Dockerfile.detector
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - detector
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    restart: unless-stopped 